In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from scipy.stats import sem
import warnings
import csv

In [5]:
teams_df = pd.read_csv("MLBTeamRevenues.csv")
teams_df.head()

,Year,Tm,Lg,W,L,Finish,Playoffs,Attendance,Attend/G,Rank,Est. Payroll,PPF,BPF,Stadium,Revenue,Operating Income,Net Income
0,2019,Baltimore Orioles,AL East,54,108,5,NaN,"1,307,807","16,146",14th of 15,"$82,696,100",102,99,Oriole Park at Camden Yards,NaN,NaN,NaN
1,2018,Baltimore Orioles,AL East,47,115,5,NaN,"1,564,192","19,311",14th of 15,"$141,555,833",100,98,Oriole Park at Camden Yards,251.0,-6.5,NaN
2,2017,Baltimore Orioles,AL East,75,87,5,NaN,"2,028,424","25,042",12th of 15,"$161,621,633",99,97,Oriole Park at Camden Yards,252.0,-26.0,NaN
3,2016,Baltimore Orioles,AL East,89,73,2,Lost ALWC (1-0),"2,172,344","26,819",10th of 15,"$153,744,833",102,102,Oriole Park at Camden Yards,253.0,-2.1,NaN
4,2015,Baltimore Orioles,AL East,81,81,3,NaN,"2,281,202","29,246",8th of 15,"$112,989,833",102,102,Oriole Park at Camden Yards,239.0,8.8,NaN

In [6]:
teams = teams_df.Tm.unique()
years = teams_df.Year.unique()
teams

array(['Baltimore Orioles', 'Chicago White Sox', 'Chicago Cubs',
       'Arizona\xa0Diamondbacks', 'Arizona Diamondbacks',
       'Boston Red Sox', 'Cleveland Indians', 'Tampa Bay Rays',
       'Washington Nationals', 'Montreal Expos', 'Texas Rangers',
       'Toronto Blue Jays', 'Cincinnati Reds', 'St Louis Cardinals',
       'San Francisco Giants', 'Seattle Mariners',
       'Philadelphia Phillies', 'Pittsburgh Pirates', 'Colorado Rockies',
       'Oakland Athletics', 'New York Yankees', 'New York Mets',
       'Miami Marlins', 'Minnesota Twins', 'Detroit Tigers',
       'Milwaukee Brewers', 'Los Angeles Angels', 'Houston Astros',
       'Los Angeles Dodgers', 'Kansas City Royals', 'Atlanta Braves'],
      dtype=object)

In [ ]:
#bar charts for revenues, payroll, wins, and operating income per team over 2002-2018
revenue = []
payroll = []
wins = []
op_inc = []

for t in teams:
    df_team = teams_df[teams_df.Tm == t]
    revenue.append(df_team['Revenue'])
    payroll.append(df_team['Est. Payroll'])
    wins.append(df_team['W'])
    op_inc.append(df_team['Operating Income'])
    fig,ax = plt.subplots()
    for y in years:
        ax.bar(revenue, years, color='r', alpha=0.5, align="center")
        plt.ylabel("Revenue in $Millions")
        plt.xlabel("Year")
        plt.title("A Team's Revenue from 2002 - 2018")
        for i, v in enumerate(diff_per_game):
            ax.text(v, i + .25, str(v), color='blue', fontweight='bold')
        plt.show()
        # tick_locations = [value for value in x]
        # plt.xticks(tick_locations, x)
        #y = [34, 34, 83, 63, 55, 60, 30, 66, 62, 83, 50]
        #x = array([8673, 8342, 9772, 9847, 8593, 8634, 9931, 9885, 9925, 9823, 8586], dtype=int64)
        plt.savefig("DomTeamsGoalDiff.png")

In [ ]:
#bar charts for revenues, payroll, wins, and operating income per year comparing all teams

In [ ]:
#bar charts for cumulative revenues, payroll, wins, and operating income per year for all teams